global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
- job_name: eureka
  eureka_sd_configs:
    - server: "http://host.docker.internal:11001/eureka"

- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['host.docker.internal:11004']